name: postgressd-rw
version: v1
type: instance-secret
description: Read-only secret for Postgres database
layer: user
instance-secret:
  type: key-value-properties
  acl: rw
  data:
    username:
    password:
